name: Notify external contributions
on:
  issues:
    types: [opened]
  discussion:
    types: [created]
  pull_request_target:
    types: [opened,reopened,review_requested,ready_for_review]

jobs:
  notify-external-contributions:
    if: github.repository_owner == 'betterscientificsoftware'
    runs-on: ubuntu-latest
    steps:
      - name: Check user for team affiliation
        uses: tspascoal/get-user-teams-membership@v2
        id: teamAffiliation
        with:
          username: ${{ github.actor }}
          team: 'bssw-editorial-board'
          GITHUB_TOKEN: ${{ secrets.TEAM_MEMBERSHIP_PAT }}
      - name: Add label if user is not member
        if: ${{ steps.teamAffiliation.outputs.isTeamMember == 'false' }}
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            external contribution
      - name: Send mail if user is not member
        if: ${{ steps.teamAffiliation.outputs.isTeamMember == 'false' }}
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{ secrets.MCM86_MAIL_USERNAME }}
          # Optional (recommended) mail server password:
          password: ${{ secrets.MCM86_MAIL_PASSWORD }}
          # Required mail subject:
          subject: External contribution detected
          # Required recipients' addresses:
          to: bssw-editorial@lists.mcs.anl.gov
          # Required sender full name (address can be skipped):
          from: notify-external-contrib.yml bssw.io action
          # Any event could have triggered. Just output union of all possible.
          # Only one of the three outputs is applicable.
          # Not applicable items generate whitespace.
          body: |
            There is an external contribution from user with GitHub user handle ${{ github.actor }}
            The item contributed is...
            ${{ github.event.issue.html_url }}
            ${{ github.event.pull_request.html_url }}
            ${{ github.event.discussion.html_url }}
